In [ ]:
# keras_server.py 

# Python program to expose a ML model as flask REST API 
import tensorflow as tf 
# import the necessary modules 
import numpy as np 
import flask 
import io 
# import the necessary packages
from keras.models import load_model
#from pyimagesearch import config
import imutils
import cv2
# Create Flask application and initialize Keras model 
app = flask.Flask(__name__) 
model1 = None

# Function to Load the model 
def load_model1(): 
    
    # global variables, to be used in another function 
    global model1
    model1 = load_model('/root/Python code/KYC Detect/mdl_wts_1.hdf5') 
    global graph 
    graph = tf.get_default_graph() 
# Every ML/DL model has a specific format 
# of taking input. Before we can predict on 
# the input image, we first need to preprocess it. 
def prepare_image(image, target): 
	if image.mode != "RGB": 
		image = image.convert("RGB") 
	
	# Resize the image to the target dimensions 
	image = image.resize(target) 
	
	# PIL Image to Numpy array 
	image = img_to_array(image) 
	
	# Expand the shape of an array, 
	# as required by the Model 
	image = np.expand_dims(image, axis = 0) 
	
	# preprocess_input function is meant to 
	# adequate your image to the format the model requires 
	image = imagenet_utils.preprocess_input(image) 

	# return the processed image 
	return image 

# Now, we can predict the results. 
@app.route("/", methods =["POST"]) 
def predict(): 
    data = {} # dictionary to store result 
    data["success"] = False

    # Check if image was properly sent to our endpoint 
    if flask.request.method == "POST": 
        if flask.request.files.get("image"): 
            image = flask.request.files["image"].read() 
            print('1',type(image))
            
            nparr = np.fromstring(image, np.uint8)
            print('2',nparr,type(nparr))
            image = cv2.imdecode(nparr, flags=1) # cv2.IMREAD_COLOR
#             image = Image.open(io.BytesIO(image)) 
            print('3',type(image),image)
#             image = image.convert("RGB")
#             print('3',type(image))
#             output = image.copy()
#             output = imutils.resize(output, width=400)
#             # our model was trained on RGB ordered images but OpenCV represents
            # images in BGR order, so swap the channels, and then resize to
            # 224x224 (the input dimensions for VGG16)
            #image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
            image = cv2.resize(image, (224, 224))
            print('final image',image)
            # convert the image to a floating point data type and perform mean
            # subtraction
            # load the trained model from disk
            CLASSES = ["aadhar","DL","pan"]
            print("[INFO] loading model...",model1)
            # pass the image through the network to obtain our predictions
            with graph.as_default(): 
				#preds = model.predict(image) 
                preds = model1.predict(np.expand_dims(image, axis=0))[0]
            i = np.argmax(preds)
            label = CLASSES[i]
            # draw the prediction on the output image
            text = "{}: {:.2f}%".format(label, preds[i] * 100)
            #cv2.putText(output, text, (3, 20), cv2.FONT_HERSHEY_SIMPLEX, 0.5,(0, 255, 0), 2)


            if (preds[i]*100)>90:
                print(label, preds[i]*100)
            else:
                print('Other')
            print(text)
            data["success"] = True

	# return JSON response 
    return flask.jsonify(data) 
    



if __name__ == "__main__": 
    print(("* Loading Keras model and Flask starting server...please wait until server has fully started")) 
    load_model1() 
    print('Model loaded')
    app.run(host='0.0.0.0') 


* Loading Keras model and Flask starting server...please wait until server has fully started
Model loaded
 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
27.6.224.104 - - [03/Mar/2020 07:06:46] "GET / HTTP/1.1" 405 -


In [ ]:
# keras_server.py 

# Python program to expose a ML model as flask REST API 
import tensorflow as tf 
# import the necessary modules 
import numpy as np 
import flask 
import io 
from flask import render_template
# import the necessary packages
from keras.models import load_model
#from pyimagesearch import config
import imutils
import cv2
import base64
import PIL
# Create Flask application and initialize Keras model 
app = flask.Flask(__name__) 
model1 = None

# Function to Load the model 
def load_model1(): 
    
    # global variables, to be used in another function 
    global model1
    model1 = load_model('/root/Python code/KYC Detect/mdl_wts_1.hdf5') 
    global graph 
    graph = tf.get_default_graph() 
# Every ML/DL model has a specific format 
# of taking input. Before we can predict on 
# the input image, we first need to preprocess it. 
def prepare_image(image, target): 
	if image.mode != "RGB": 
		image = image.convert("RGB") 
	
	# Resize the image to the target dimensions 
	image = image.resize(target) 
	
	# PIL Image to Numpy array 
	image = img_to_array(image) 
	
	# Expand the shape of an array, 
	# as required by the Model 
	image = np.expand_dims(image, axis = 0) 
	
	# preprocess_input function is meant to 
	# adequate your image to the format the model requires 
	image = imagenet_utils.preprocess_input(image) 

	# return the processed image 
	return image 

# Now, we can predict the results. 
@app.route("/prediction", methods =["POST"]) 
def predict(): 
    data = {} # dictionary to store result 
    data["success"] = False

    # Check if image was properly sent to our endpoint 
    if flask.request.method == "POST": 
        if flask.request.files.get("image"): 
            image = flask.request.files["image"]
            print('1',type(image))
            
            image.save(image.filename);
            image_filename = image.filename;
            with open(image_filename, "rb") as im:
                b = base64.b64encode(im.read())
                image = b
            nparr = np.fromstring(image, np.uint8)
            print('2',nparr,type(nparr))
            image1 = cv2.imdecode(nparr, flags=1) # cv2.IMREAD_COLOR
#             image = Image.open(io.BytesIO(image)) 
            print('3',type(image1),image1)
#           
#             image = image.convert("RGB")
#             print('3',type(image))
#             output = image.copy()
#             output = imutils.resize(output, width=400)
#             # our model was trained on RGB ordered images but OpenCV represents
            # images in BGR order, so swap the channels, and then resize to
            # 224x224 (the input dimensions for VGG16)
            #image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
            image = cv2.resize(image, (224, 224))
            print('final image',image)
            # convert the image to a floating point data type and perform mean
            # subtraction
            # load the trained model from disk
            CLASSES = ["aadhar","DL","pan"]
            print("[INFO] loading model...",model1)
            # pass the image through the network to obtain our predictions
            with graph.as_default(): 
				#preds = model.predict(image) 
                preds = model1.predict(np.expand_dims(image, axis=0))[0]
            i = np.argmax(preds)
            label = CLASSES[i]
            # draw the prediction on the output image
            text = "{}: {:.2f}%".format(label, preds[i] * 100)
            #cv2.putText(output, text, (3, 20), cv2.FONT_HERSHEY_SIMPLEX, 0.5,(0, 255, 0), 2)


            if (preds[i]*100)>90:
                print(label, preds[i]*100)
            else:
                print('Other')
            print(text)
            data["success"] = True

	# return JSON response 
    dict_data = {}
    dict_data['data'] = flask.jsonify(data) 
    dict_data['label'] = label
    dict_data['image_name'] = image_filename;
    return rennder_template('display.html', dict_data = dict_data);





if __name__ == "__main__": 
    print(("* Loading Keras model and Flask starting server...please wait until server has fully started")) 
    load_model1() 
    print('Model loaded')
    app.run(host='0.0.0.0') 


* Loading Keras model and Flask starting server...please wait until server has fully started
Model loaded
 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
27.6.224.104 - - [03/Mar/2020 06:13:19] code 400, message Bad request syntax ('\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03')
27.6.224.104 - - [03/Mar/2020 06:13:19] code 400, message Bad request syntax ('\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03|\x04I¹Hz\xad\x02\x83yÍýÍ!\x11/Ak¥Õ\x07÷EOSÑ\x1b~>\x89õ4 ]ì±\x8cr½ww-çS=9\x83H?°\x1f£\x9b\x0c\x8a3O\x92Ý>\xadÅ°tÀ\x00"ÚÚ\x13\x01\x13\x02\x13\x03À+À/À,À0̨̩À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x00')
27.6.224.104 - - [03/Mar/2020 06:13:19] "ü" HTTPStatus.BAD_REQUEST -
27.6.224.104 - - [03/Mar/2020 06:13:19] "ü|I¹Hz­ƒyÍýÍ!/Ak¥Õ÷EOSÑ~>‰õ4 ]챌r½ww-çS=9ƒH?°£›Š3O’Ý>­Å°tÀ"ÚÚÀ+À/À,À0̨̩ÀÀœ/5" HTTPStatus.BAD_REQUEST -
27.6.224.104 - - [03/Mar/2020 06:13:20] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03\x93\x10÷ç(Ö½<+Ã3\x99Þ')
27.6.224.104 - - [03/Mar/2020 06:13:20] "ü“÷ç(Ö½<+Ã3™Þ	XÛíí" HTTPStatus.BAD_REQ

In [ ]:
# keras_server.py 

# Python program to expose a ML model as flask REST API 
import tensorflow as tf 
# import the necessary modules 
import numpy as np 
import flask 
import io 
from flask import render_template
# import the necessary packages
from keras.models import load_model
#from pyimagesearch import config
import imutils
import cv2
# Create Flask application and initialize Keras model 
app = flask.Flask(__name__) 
model1 = None

# Function to Load the model 
def load_model1(): 
    
    # global variables, to be used in another function 
    global model1
    model1 = load_model('/root/Python code/KYC Detect/mdl_wts_1.hdf5') 
    global graph 
    graph = tf.get_default_graph() 
# Every ML/DL model has a specific format 
# of taking input. Before we can predict on 
# the input image, we first need to preprocess it. 
def prepare_image(image, target): 
	if image.mode != "RGB": 
		image = image.convert("RGB") 
	
	# Resize the image to the target dimensions 
	image = image.resize(target) 
	
	# PIL Image to Numpy array 
	image = img_to_array(image) 
	
	# Expand the shape of an array, 
	# as required by the Model 
	image = np.expand_dims(image, axis = 0) 
	
	# preprocess_input function is meant to 
	# adequate your image to the format the model requires 
	image = imagenet_utils.preprocess_input(image) 

	# return the processed image 
	return image 
@app.route("/")
def login1():
      return render_template('index.html')

# Now, we can predict the results. 
@app.route("/prediction", methods =["GET","POST"]) 
def predict(): 
    data = {} # dictionary to store result 
    data["success"] = False

    # Check if image was properly sent to our endpoint 
    if flask.request.method == "POST": 
        if flask.request.files.get("image"): 
            image = flask.request.files["image"].read() 
            print('1',type(image))
            
            nparr = np.fromstring(image, np.uint8)
            print('2',nparr,type(nparr))
            image = cv2.imdecode(nparr, flags=1) # cv2.IMREAD_COLOR
#             image = Image.open(io.BytesIO(image)) 
            print('3',type(image),image)
#             image = image.convert("RGB")
#             print('3',type(image))
#             output = image.copy()
#             output = imutils.resize(output, width=400)
#             # our model was trained on RGB ordered images but OpenCV represents
            # images in BGR order, so swap the channels, and then resize to
            # 224x224 (the input dimensions for VGG16)
            #image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
            image = cv2.resize(image, (224, 224))
            print('final image',image)
            # convert the image to a floating point data type and perform mean
            # subtraction
            # load the trained model from disk
            CLASSES = ["aadhar","DL","pan"]
            print("[INFO] loading model...",model1)
            # pass the image through the network to obtain our predictions
            with graph.as_default(): 
				#preds = model.predict(image) 
                preds = model1.predict(np.expand_dims(image, axis=0))[0]
            i = np.argmax(preds)
            label = CLASSES[i]
            # draw the prediction on the output image
            text = "{}: {:.2f}%".format(label, preds[i] * 100)
            #cv2.putText(output, text, (3, 20), cv2.FONT_HERSHEY_SIMPLEX, 0.5,(0, 255, 0), 2)


            if (preds[i]*100)>90:
                print(label, preds[i]*100)
            else:
                print('Other')
            print(text)
            data["success"] = True
    dict_data = {}
    dict_data['preds'] = preds[i]*100;
    dict_data['data'] = flask.jsonify(data) 
    dict_data['label'] = label
	# return JSON response 
    return render_template('display.html',dict_data=dict_data) 
    



if __name__ == "__main__": 
    print(("* Loading Keras model and Flask starting server...please wait until server has fully started")) 
    load_model1() 
    print('Model loaded')
    app.run(host='0.0.0.0') 


Using TensorFlow backend.


* Loading Keras model and Flask starting server...please wait until server has fully started
Model loaded
 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
27.6.224.104 - - [03/Mar/2020 08:52:06] "GET / HTTP/1.1" 200 -
27.6.224.104 - - [03/Mar/2020 08:52:07] "GET /vendor/bootstrap/css/bootstrap.min.css HTTP/1.1" 404 -
27.6.224.104 - - [03/Mar/2020 08:52:07] "GET /fonts/font-awesome-4.7.0/css/font-awesome.min.css HTTP/1.1" 404 -
27.6.224.104 - - [03/Mar/2020 08:52:07] "GET /vendor/animate/animate.css HTTP/1.1" 404 -
27.6.224.104 - - [03/Mar/2020 08:52:07] "GET /fonts/Linearicons-Free-v1.0.0/icon-font.min.css HTTP/1.1" 404 -
27.6.224.104 - - [03/Mar/2020 08:52:07] "GET /vendor/css-hamburgers/hamburgers.min.css HTTP/1.1" 404 -
27.6.224.104 - - [03/Mar/2020 08:52:07] "GET /vendor/animsition/css/animsition.min.css HTTP/1.1" 404 -
27.6.224.104 - - [03/Mar/2020 08:52:07] "GET /vendor/select2/select2.min.css HTTP/1.1" 404 -
27.6.224.104 - - [03/Mar/2020 08:52:07] "GET /vendor/daterangepicker/daterangepicker.css HTTP/1.1" 404 -
27.6.224.104 - - [03/Mar/2020 08:52:07] "GET /css/main.css HTTP

1 <class 'bytes'>
2 [137  80  78 ...  66  96 130] <class 'numpy.ndarray'>
3 <class 'numpy.ndarray'> [[[189 194 185]
  [178 181 172]
  [163 163 157]
  ...
  [252 232 197]
  [255 247 216]
  [255 255 233]]

 [[180 183 174]
  [161 164 155]
  [147 145 137]
  ...
  [227 208 171]
  [243 224 191]
  [255 244 212]]

 [[148 149 139]
  [148 147 137]
  [151 149 139]
  ...
  [197 177 136]
  [209 190 153]
  [224 205 170]]

 ...

 [[194 177 186]
  [201 184 193]
  [211 192 201]
  ...
  [239 206 160]
  [239 208 163]
  [242 210 167]]

 [[226 220 225]
  [202 195 200]
  [198 188 194]
  ...
  [223 197 160]
  [216 191 157]
  [247 223 195]]

 [[231 230 232]
  [205 204 206]
  [200 195 197]
  ...
  [238 216 181]
  [230 209 182]
  [255 240 219]]]
final image [[[187 192 183]
  [172 174 166]
  [157 154 149]
  ...
  [223 203 166]
  [254 241 208]
  [255 254 231]]

 [[181 184 175]
  [161 162 153]
  [151 148 142]
  ...
  [219 199 160]
  [242 225 191]
  [254 245 216]]

 [[163 165 156]
  [152 152 143]
  [154 150 143]
  

/root/anaconda3/envs/myenv/lib/python3.6/site-packages/ipykernel_launcher.py:66: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
27.6.224.104 - - [03/Mar/2020 08:52:27] "POST /prediction HTTP/1.1" 200 -
27.6.224.104 - - [03/Mar/2020 08:52:28] "GET /vendor/bootstrap/css/bootstrap.min.css HTTP/1.1" 404 -
27.6.224.104 - - [03/Mar/2020 08:52:28] "GET /fonts/font-awesome-4.7.0/css/font-awesome.min.css HTTP/1.1" 404 -
27.6.224.104 - - [03/Mar/2020 08:52:28] "GET /fonts/Linearicons-Free-v1.0.0/icon-font.min.css HTTP/1.1" 404 -
27.6.224.104 - - [03/Mar/2020 08:52:28] "GET /vendor/animate/animate.css HTTP/1.1" 404 -
27.6.224.104 - - [03/Mar/2020 08:52:28] "GET /vendor/css-hamburgers/hamburgers.min.css HTTP/1.1" 404 -
27.6.224.104 - - [03/Mar/2020 08:52:28] "GET /vendor/animsition/css/animsition.min.css HTTP/1.1" 404 -


pan 98.98900985717773
pan: 98.99%


27.6.224.104 - - [03/Mar/2020 08:52:28] "GET /vendor/select2/select2.min.css HTTP/1.1" 404 -
27.6.224.104 - - [03/Mar/2020 08:52:28] "GET /vendor/daterangepicker/daterangepicker.css HTTP/1.1" 404 -
27.6.224.104 - - [03/Mar/2020 08:52:28] "GET /css/main.css HTTP/1.1" 404 -
27.6.224.104 - - [03/Mar/2020 08:52:28] "GET /css/util.css HTTP/1.1" 404 -
27.6.224.104 - - [03/Mar/2020 08:52:28] "GET /vendor/jquery/jquery-3.2.1.min.js HTTP/1.1" 404 -
27.6.224.104 - - [03/Mar/2020 08:52:28] "GET /vendor/animsition/js/animsition.min.js HTTP/1.1" 404 -
27.6.224.104 - - [03/Mar/2020 08:52:28] "GET /vendor/bootstrap/js/popper.js HTTP/1.1" 404 -
27.6.224.104 - - [03/Mar/2020 08:52:28] "GET /vendor/bootstrap/js/bootstrap.min.js HTTP/1.1" 404 -
27.6.224.104 - - [03/Mar/2020 08:52:28] "GET /images/T.jpg HTTP/1.1" 404 -
27.6.224.104 - - [03/Mar/2020 08:52:28] "GET /images/logo.png HTTP/1.1" 404 -
27.6.224.104 - - [03/Mar/2020 08:52:28] "GET /vendor/select2/select2.min.js HTTP/1.1" 404 -
27.6.224.104 - - [0